version: '3'
services:
    nginx:
        build: ./nginx
        ports:
          - "80:80"
        depends_on:
          - php
        volumes:
         - ./contents/{pj-source-path}:/var/www/html

    php:
        build: ./php
        env_file: ./mysql/.env_sample
        environment:
         DATABASE_HOST: mysql
        depends_on:
         - mysql
        volumes:
         - ./contents/{pj-source-path}:/var/www/html

    mysql:
        image: mysql:5.7.21
        env_file: ./mysql/.env_sample
        ports:
         - "3306:3306"
        volumes:
         - ./mysql/{import-sql}:/docker-entrypoint-initdb.d/initial.sql
